/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PX2_Phoenix3d_Library_PX2Renderer */

#ifndef _Included_PX2_Phoenix3d_Library_PX2Renderer
#define _Included_PX2_Phoenix3d_Library_PX2Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PX2_Phoenix3d_Library_PX2Renderer
 * Method:    nativeOdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PX2_Phoenix3d_Library_PX2Renderer_nativeOdle
  (JNIEnv *, jclass);

/*
 * Class:     PX2_Phoenix3d_Library_PX2Renderer
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_PX2_Phoenix3d_Library_PX2Renderer_nativeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     PX2_Phoenix3d_Library_PX2Renderer
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PX2_Phoenix3d_Library_PX2Renderer_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     PX2_Phoenix3d_Library_PX2Renderer
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PX2_Phoenix3d_Library_PX2Renderer_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     PX2_Phoenix3d_Library_PX2Renderer
 * Method:    nativeTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PX2_Phoenix3d_Library_PX2Renderer_nativeTerm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
