/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phoenix3d_px2_library_PX2Natives */

#ifndef _Included_phoenix3d_px2_library_PX2Natives
#define _Included_phoenix3d_px2_library_PX2Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOdle
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeOnTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeOnTerm
  (JNIEnv *, jclass);

/*
 * Class:     phoenix3d_px2_library_PX2Natives
 * Method:    nativeSetResourcePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phoenix3d_px2_library_PX2Natives_nativeSetResourcePath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
